name: Test & Publish to Cloudflare
author: carlosdevpereira
description: This action runs the test command of a repository, generates the test coverage report, uploads the report to cloudflare pages and comments the results on available pull requests.

runs:
  using: "node16"
  main: "index.js"

inputs:
  testCommand:
    description: "The command used to run the unit tests of the repository (needs to be the explicit command and not an alias like `npm run test`)."
    required: false
    default: "./node_modules/jest/bin/jest.js --no-cache --detectOpenHandles --coverage"
  cloudflareProjectName:
    description: "The name of the project on Cloudflare that will receive the coverage report."
    required: true
  cloudflareApiToken:
    description: "The API Token that will be used to upload the coverage report to Cloudflare."
    required: true
  cloudflareAccountId:
    description: "The Account ID that will be used to upload the coverage report to Cloudflare."
    required: true
  githubToken:
    description: "The github token that will be used to comment the results on available pull requests."
    required: true
  baseCloudflareDeploymentUrl:
    description: "The base URL configured on the target Cloudflare project from which the deployments will be served - It can also be a custom domain configured on the target project. (defaults to https://${cloudflareProjectName}.pages.dev)"
    required: false

outputs:
  coverage:
    description: "The final coverage percentage - average between the coverage values for Statements/Branches/Functions and Lines."
  reportUrl:
    description: "The final URL to the coverage report served by Cloudflare."
  affectedPullRequestUrls:
    description: "Pull request URL's that this action wrote comments on."
