on:
  push:
    branches:
      - main

name: Release
jobs:
  release-please:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          prerelease: false
          release-type: node
          package-name: test-publish-to-cloudflare
          default-branch: main
          pull-request-title-pattern: "🚀 Release ${component} ${version}"
          changelog-types: '[{"type":"feat","section":"✨ Features","hidden":false},{"type":"fix","section":"🚨 Bug Fixes","hidden":false},{"type":"hotfix","section":"🚒 Hotfixes","hidden":false},{"type":"chore","section":"👷 Maintenance","hidden":false},{"type":"docs","section":"📚 Documentation","hidden":false}]'
